FROM node:18-alpine


WORKDIR /app


RUN apk update && \
    apk add --no-cache \
    g++ \
    openjdk11-jdk \
    python3


COPY package*.json ./


RUN npm install


COPY . .


EXPOSE 5000


CMD ["node" , "index.js"]
